### PR TITLE
Unit Testing SpentCointState.cs

### PR DESCRIPTION
**Pull request by markved**
Review deserialize and serialize methods. The actual methods itself need to handle a few exceptions. Rest other test methods look straight forward.

### CODE REVIEW

**Comment by AshRolls** [comment]
- Some tests are failing on the CI (see report above).
- Deserialize doesn't check the property values of the deserialized object
- Serialized dataArray length is 44, but requiredData length is longer than this
- We only check the first 44 chars of the the requiredData array.
- We shouldn't have the try / catch blocks {}, exceptions will already fail the tests

**Comment by AshRolls** [comment]
- Missing tests for Size
- In SerilializeSCS test, requiredData and dataArray length are not equal.
- In DeserializeSCS test we should have a using with the new MemoryStream()
- In setupSpentCoinStateWithValues we should use actual ushort and uint values rather than just new(), and adjust the serialize / deserialize appropriately.
- Some minor spacing and indentation issues

**Comment by AshRolls** [comment]
Ok almost there, just a few more

- We don't test size when `Items` contains data
- Deserialize dataArray looks like it contains too many bytes. I recommend you use the same byte array as you use in `Serialize`, and adjust the assertion.

**Comment by canesin** [comment]
congrats @markved in being open to learn and improve on the testing ;) .. I was reviewing this week work and noticed the constant improvement, keep it going :+1:

**Comment by markved** [comment]
Thanks, @canesin and @AshRolls :)... Glad to be part of this group!

**Pull request merged**
