### PR TITLE
Add NLog dependency to neo

### PR DESCRIPTION
**Pull request by crypt0m1nd3r**
- Added NLog 5 dependency (config file and XSD are with executables)
- Added some logging statements in LevelDBBlockchain.cs
- Removed unnecessary net461 framework since it isn't needed and does not work on non-Windows platforms such as macOS.

### CODE REVIEW

**Comment by AshRolls** [comment]
@erikzhang do you have any specific objection to the removal of the .net641 framework from neo.csproj ?

**Comment by AshRolls** [comment]
We also need to consider if we want to add a new dependency (to nlog) in the core code. Generally we should avoid external dependencies wherever possible.

If we do remove the .net641 dependency then we will also need to remove all the code blocks where we switch compile based on target.

**Comment by canesin** [comment]
@AshRolls my view is that core code should not have dependencies external to .NET Core. .. it already covers a lot of ground, if it is in a separated project (like the unit testing)..  OK ..
Don't .NET Core have a logging feature in it ?

**Comment by crypt0m1nd3r** [comment]
@canesin -- there's https://github.com/net-commons/common-logging and https://github.com/aspnet/Logging which could be used in core to abstract the actual logger being used.

Both support NLog.

**Comment by canesin** [comment]
@crypt0m1nd3r https://github.com/aspnet/Logging looks to be the only official .. using the ILoggerFactory .. can we remove the NLog dependency from core with it ?

**Comment by crypt0m1nd3r** [comment]
@canesin -- yes, looking into doing that.  The neo-cli/neo-gui will need some actual logger (like NLog) in the build, but all the NEO code should use an interface that is agnostic of the actual implementation.

**Comment by canesin** [comment]
Thanks @crypt0m1nd3r that is awesome! I will close this PR then, and you create a new one with the abstraction.

**Pull request closed without merging**
